configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/embeddings-corporation%2Fdatagyro-d657e3f0c9e3da9ff17ce28df9cbec4c11c3dce60f4ed58a881d564310a6ee54.yml
openapi_spec_hash: 23a429284159c9ec257ee54ac7d7824f
config_hash: cfc2fd0b3a919bc4d29def0eb76c8329
